### ISSUE TITLE
Fail to download R when binary isn't available

### ISSUE THREAD

**Issue by lambdamoses** [grimbough/bioc-actions#10]
Hi, thanks for the really helpful setup-bioc workflow! R 4.2.3 was released on March 15, and it has been causing a 404 error when downloading R to my GitHub Action with a Mac runner: https://github.com/pachterlab/voyager/actions/runs/4452116319/jobs/7819479965

However, the setup-bioc workflow does not have a parameter to set the version of R, because Bioconductor versions are tied to R major versions so you have script to determine the version of R to use. But not minor versions, so Bioconductor 3.16 works with 4.2.x. Then is it possible for you to allow users to specify R minor versions that are compatible with a given Bioconductor version? So before we get R 4.2.3 Mac binary, we can keep on using R 4.2.2 for this action using Bioconductor 3.16. Thanks!

**Comment by lambdamoses** [comment]
It works now. But it would be nice if the lag in binary release is taken into account for future versions of R.

**Comment by grimbough** [comment]
Hi @lambdamoses thanks for the report, I'm glad you find the actions useful.  However I think this is actually an issue with https://github.com/r-lib/actions/tree/v2-branch/setup-r

I take the R version from this file that maps between Bioc version and R version (https://github.com/grimbough/bioc-actions/blob/v1-branch/setup-bioc/bioc-version-map.csv)  As you can see, it doesn't use the patch version of R, so it's always requesting R 4.2 and letting r-libs/setup-r do the rest.  

You can see the version request in your workflow at https://github.com/pachterlab/voyager/actions/runs/4452116319/jobs/7819479965#step:4:24 It looks to me like that action is a bit premature about switching from 4.2.2 to 4.2.3 for Mac.

I'll see if there's anything obvious I can do my end in case of failure like this.
